spring.application.name=food-delivery
spring.datasource.url= jdbc:postgresql://localhost:5432/food-delivery-DB01
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

server.port=8081
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect